site_name: Flotiq Developer Documentation
site_url: https://flotiq.com/docs/
dev_addr: 0.0.0.0:4000
theme:
     name: 'material'
     logo: 'API/images/f.png'
     custom_dir: 'theme'
     palette:
             primary: 'teal'
     feature:
             tabs: true
plugins:
  - search
  - awesome-pages

extra_css:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
  - 'css/flotiq.css'
    #  - https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.30.0/codemirror.min.css

google_analytics:
  - 'UA-10126793-18'
  - 'auto'

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - meta
  - toc
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_javascript:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
  - 'js/flotiq.js'
    #- https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.30.0/codemirror.min.js
    #- https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.30.0/mode/javascript/javascript.min.js

extra:
  disqus: 'flotiq'
